# See documentation in scripts/buildbot/README
name: SSH and Execute Build Script

on:
  pull_request:
    types: [opened, synchronize, reopened]

# To cancel a currently running workflow from the same PR, branch or tag when a new workflow is triggered
# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Execute build script via SSH
        run: |
          ssh axon 'sh buildbot/build_srun.sh ${{ github.event.pull_request.number }}'
